Repository BinaryStudioAcademy/bsa-2021-infostack, pull requests merged in 2021-09, with the labels that each got.

#306 Fix: removed plus button from pinned pages
  frontend/src/components/common/with-header/components/toolbar/components/page-item/page-item.tsx
  frontend/src/components/common/with-header/components/toolbar/components/pages-list/pages-list.tsx
  frontend/src/components/common/with-header/components/toolbar/toolbar.tsx
Labels: bug

#304 fix: delete page
  backend/src/data/entities/page.ts
  backend/src/data/entities/recent-pages.ts
  backend/src/data/migrations/1630476711471-add-recent-page-cascade-delete.ts
Labels: bug

#309 Fix: pinned pages' titles don't update on edit
  backend/src/data/repositories/user.repository.ts
  frontend/src/store/pages/actions.ts
Labels: bug

#303 New/mobile page list
  mobile/.stylelintrc
  mobile/android/app/build.gradle
  mobile/metro.config.js
  mobile/package-lock.json
  mobile/package.json
  mobile/src/common/enums/color.enum.ts
  mobile/src/common/enums/index.ts
  mobile/src/components/app/app.tsx
  mobile/src/components/page-list/page-list.tsx
  mobile/src/components/pages/components/page-list-item.tsx
  mobile/src/components/pages/components/page-list.tsx
  mobile/src/components/pages/pages.tsx
  mobile/src/components/pages/screens/expanded-page.tsx
  mobile/src/components/pages/screens/root-pages.tsx
  mobile/src/components/workspaces/components/workspace-list-item.tsx
  mobile/src/components/workspaces/workspaces.tsx
  mobile/src/navigation/page-list-stack.ts
  mobile/src/navigation/root-stack.ts
  mobile/src/services/page.service.ts
  mobile/src/store/index.ts
  mobile/src/store/pages/index.ts
  mobile/src/store/pages/selectors.ts
  mobile/src/store/selectors.ts
  package-lock.json
  package.json
  shared/src/common/enums/index.ts
  shared/src/common/enums/reducer-name/index.ts
  shared/src/common/enums/reducer-name/reducer-name.enum.ts
  shared/src/common/enums/request-status/index.ts
  shared/src/common/enums/request-status/request-status.enum.ts
Labels: enhancement

#318 Fix: duplicate skills in workspace
  backend/src/services/skill.service.ts
Labels: bug

#319 Fix: redirect to login on invite link
  backend/src/common/interfaces/auth/index.ts
  backend/src/services/user.service.ts
  frontend/src/common/interfaces/user/index.ts
  frontend/src/components/auth/sign-up-invite/sign-up-invite.tsx
  frontend/src/services/user-api.service.ts
  shared/src/common/interfaces/auth/index.ts
  shared/src/common/interfaces/auth/invite-user.interface.ts
Labels: bug

#320 New/ability to authorize mobile
  mobile/index.js
  mobile/metro.config.js
  mobile/package-lock.json
  mobile/package.json
  mobile/src/assets/svg/logo_dark.svg
  mobile/src/common/enums/cookie-variable.enum.ts
  mobile/src/common/enums/emitter-events.enum.ts
  mobile/src/common/enums/file.enum.ts
  mobile/src/common/enums/http.enum.ts
  mobile/src/common/enums/index.ts
  mobile/src/common/enums/local-storage.enum.ts
  mobile/src/common/interfaces/auth.interface.ts
  mobile/src/common/interfaces/index.ts
  mobile/src/common/interfaces/user.interface.ts
  mobile/src/common/interfaces/workspace.interface.ts
  mobile/src/common/types/http-options.type.ts
  mobile/src/common/types/index.ts
  mobile/src/common/validations/index.ts
  mobile/src/components/app/app.tsx
  mobile/src/components/auth/index.ts
  mobile/src/components/auth/login/index.ts
  mobile/src/components/auth/login/login.tsx
  mobile/src/components/workspaces/workspaces.tsx
  mobile/src/declarations/declarations.d.ts
  mobile/src/exceptions/exceptions.ts
  mobile/src/hooks/form.hooks.ts
  mobile/src/hooks/index.ts
  mobile/src/hooks/react.hooks.ts
  mobile/src/index.tsx
  mobile/src/navigation/root-stack.ts
  mobile/src/services/auth.service.ts
  mobile/src/services/http.service.ts
  mobile/src/services/index.ts
  mobile/src/services/workspace.service.ts
  mobile/src/store/actions.ts
  mobile/src/store/auth/async-actions.ts
  mobile/src/store/auth/common.ts
  mobile/src/store/auth/index.ts
  mobile/src/store/auth/slice.ts
  mobile/src/store/root-reducer.ts
  mobile/src/store/workspaces/async-actions.ts
  mobile/src/store/workspaces/common.ts
  mobile/src/store/workspaces/index.ts
  mobile/src/store/workspaces/slice.ts
Labels: enhancement

#323 fix: display all pages in workspace for workspace admin
  backend/src/services/page.service.ts
Labels: bug

#330 Fix login
  backend/package-lock.json
  backend/src/services/auth.service.ts
  frontend/package-lock.json
  frontend/src/components/auth/login/login.tsx
  frontend/src/components/auth/reset-password/reset-password.tsx
  frontend/src/components/auth/sign-up/sign-up.tsx
  frontend/src/components/common/sign/sign.tsx
  frontend/src/components/common/sign/styles.module.scss
  shared/src/common/enums/http/http-error-message.enum.ts
  shared/src/common/validations/login-schema.ts
Labels: bug

#332 New: smart redirect on login
  backend/src/api/routes/auth-route.ts
  backend/src/api/routes/page-route.ts
  backend/src/services/auth.service.ts
  backend/src/services/page.service.ts
  frontend/src/common/interfaces/pages/index.ts
  frontend/src/components/auth/login-github/login-github.tsx
  frontend/src/components/auth/login-google/login-google.tsx
  frontend/src/components/auth/login/login.tsx
  frontend/src/components/common/protected-route/protected-route.tsx
  frontend/src/components/common/sign/sign.tsx
  frontend/src/components/settings/components/integration-settings/integration-settings.tsx
  frontend/src/components/workspaces/workspaces.tsx
  frontend/src/services/auth-api.service.ts
  shared/src/common/interfaces/pages/index.ts
  shared/src/common/interfaces/pages/page-requested.interface.ts
Labels: enhancement

#337 Fix github integration
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/components/auth/login-github/login-github.tsx
  frontend/src/components/settings/components/integration-settings/styles.module.scss
Labels: bug

#338 Fix integrations styles
  frontend/src/components/settings/components/integration-settings/components/select/select-repo-styles.ts
  frontend/src/components/settings/components/integration-settings/components/select/styles.module.scss
Labels: bug

#340 Fix/comment block size
  frontend/src/components/pages/components/comment-section/components/comment-form/styles.module.scss
Labels: enhancement

#345 fix: team list is updated after creation of a new team
  frontend/src/store/teams/slice.ts
Labels: bug

#336 New/mobile page search
  mobile/metro.config.js
  mobile/package-lock.json
  mobile/package.json
  mobile/src/common/constants/index.ts
  mobile/src/common/constants/search.ts
  mobile/src/common/constants/theme.ts
  mobile/src/common/enums/color.enum.ts
  mobile/src/common/enums/file.enum.ts
  mobile/src/common/enums/http.enum.ts
  mobile/src/common/enums/index.ts
  mobile/src/common/enums/local-storage.enum.ts
  mobile/src/common/interfaces/auth.interface.ts
  mobile/src/common/interfaces/index.ts
  mobile/src/common/interfaces/page.interface.ts
  mobile/src/common/types/index.ts
  mobile/src/components/app/app.tsx
  mobile/src/components/auth/index.ts
  mobile/src/components/auth/login.tsx
  mobile/src/components/auth/login/index.ts
  mobile/src/components/pages/components/page-list-item.tsx
  mobile/src/components/pages/components/page-list.tsx
  mobile/src/components/pages/pages.tsx
  mobile/src/components/pages/screens/expanded-page.tsx
  mobile/src/components/pages/screens/root-pages.tsx
  mobile/src/components/search/components/empty-list-placeholder.tsx
  mobile/src/components/search/components/search-input.tsx
  mobile/src/components/search/components/search-item.tsx
  mobile/src/components/search/search-button.tsx
  mobile/src/components/search/search.tsx
  mobile/src/components/workspaces/components/workspace-list-item.tsx
  mobile/src/components/workspaces/workspaces.tsx
  mobile/src/exceptions/http.exception.ts
  mobile/src/exceptions/index.ts
  mobile/src/hooks/store.hooks.ts
  mobile/src/index.tsx
  mobile/src/navigation/page-list-stack.ts
  mobile/src/services/auth.service.ts
  mobile/src/services/http.service.ts
  mobile/src/services/page.service.ts
  mobile/src/services/workspace.service.ts
  mobile/src/store/actions.ts
  mobile/src/store/auth/index.ts
  mobile/src/store/auth/selectors.ts
  mobile/src/store/pages/index.ts
  mobile/src/store/pages/selectors.ts
  mobile/src/store/selectors.ts
  mobile/src/store/workspaces/index.ts
Labels: enhancement

#346 fix: page title doesn't overflow
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/components/pages/components/page-content/styles.module.scss
Labels: bug

#352 Fix: profile icon and text in header dropdown
  frontend/src/components/common/with-header/components/header/components/nav-profile/nav-profile.tsx
Labels: bug

#355 Fix: list of followed pages in unfollow modal
  frontend/src/components/pages/components/page-content/page-content.tsx
Labels: bug

#360 New: unpin button next to page title in list of pinned
  frontend/src/components/common/with-header/components/toolbar/components/components.ts
  frontend/src/components/common/with-header/components/toolbar/components/cross-button/cross-button-root.tsx
  frontend/src/components/common/with-header/components/toolbar/components/page-item/page-item.tsx
  frontend/src/components/common/with-header/components/toolbar/components/pages-list/pages-list.tsx
  frontend/src/components/common/with-header/components/toolbar/toolbar.tsx
  frontend/src/store/pages/actions.ts
Labels: enhancement

#349 New/ability to open page on mobile
  frontend/src/components/settings/components/users-settings/users-settings.tsx
  mobile/package-lock.json
  mobile/package.json
  mobile/src/components/pages/components/page-list-item.tsx
  mobile/src/components/pages/components/page-list.tsx
  mobile/src/components/pages/pages.tsx
  mobile/src/components/pages/screens/expanded-page.tsx
  mobile/src/components/pages/screens/page.tsx
  mobile/src/components/pages/screens/root-pages.tsx
  mobile/src/navigation/page-list-stack.ts
  mobile/src/services/page.service.ts
  mobile/src/store/pages/action-type.enum.ts
  mobile/src/store/pages/async-actions.ts
  mobile/src/store/pages/selectors.ts
  mobile/src/store/pages/slice.ts
Labels: enhancement

#365 fix: recorded time is shown
  frontend/src/components/pages/components/comment-section/components/record-modal/record-modal.tsx
  frontend/src/components/pages/components/comment-section/components/record-modal/styles.module.scss
Labels: bug

#356 fix: upload avatar display immediately
  frontend/src/components/settings/components/profile-settings/profile-settings.tsx
Labels: bug

#367 Fix/workspace logo disappears on workspace name change
  frontend/src/components/pages/components/comment-section/components/record-modal/styles.module.scss
  frontend/src/store/workspaces/actions.ts
Labels: bug

#368 fix: modal min width added
  frontend/src/components/pages/components/comment-section/components/record-modal/record-modal.tsx
  frontend/src/components/pages/components/comment-section/components/record-modal/styles.module.scss
Labels: bug

#370 fix: time in mm-ss, modal styles changed, audio comment styles reverted
  frontend/package-lock.json
  frontend/src/components/pages/components/comment-section/components/comment/comment.tsx
  frontend/src/components/pages/components/comment-section/components/comment/styles.module.scss
  frontend/src/components/pages/components/comment-section/components/record-modal/record-modal.tsx
  frontend/src/components/pages/components/comment-section/components/record-modal/styles.module.scss
Labels: bug

#369 fix: static height for count of notifications
  frontend/src/components/common/with-header/components/header/components/nav-notification/components/icon-with-count/styles.module.scss
Labels: bug

#371 Fix: avatars position above found items in search
  frontend/src/components/settings/components/team-settings/components/item/styles.module.scss
Labels: bug

#375 Fix/markdown headers styles
  frontend/src/components/pages/components/page-content/styles.module.scss
Labels: bug

#374 Fix: replaced no permission message with 404 page
  frontend/src/components/pages/components/page-content/page-content.tsx
Labels: bug

#378 Fix/page title alignment
  frontend/src/components/pages/components/page-content/page-content.tsx
  mobile/src/components/auth/login.tsx
Labels: bug

#381 Add statistics
  backend/package-lock.json
  backend/package.json
  backend/src/api/routes/page-route.ts
  backend/src/common/interfaces/page/index.ts
  backend/src/common/mappers/page/map-recent-pages.helper.ts
  backend/src/data/repositories/page.repository.ts
  backend/src/data/repositories/recent-pages.repository.ts
  backend/src/data/repositories/team-permission.repository.ts
  backend/src/data/repositories/user-permission.repository.ts
  backend/src/services/page.service.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/interfaces/pages/index.ts
  frontend/src/common/interfaces/query/query.interface.ts
  frontend/src/components/common/with-header/components/toolbar/toolbar.tsx
  frontend/src/components/common/with-header/with-header.tsx
  frontend/src/components/pages/components/chart/chart.tsx
  frontend/src/components/pages/components/chart/styles.module.scss
  frontend/src/components/pages/components/components.ts
  frontend/src/components/pages/components/pages-recent/pages-recent.tsx
  frontend/src/components/pages/components/pages-statistic/pages-statistic.tsx
  frontend/src/components/pages/components/pages-statistic/styles.module.scss
  frontend/src/components/pages/pages.tsx
  frontend/src/components/pages/styles.module.scss
  frontend/src/services/page-api.service.ts
  frontend/src/services/user-api.service.ts
  frontend/src/store/pages/actions.ts
  frontend/src/store/pages/common.ts
  frontend/src/store/pages/slice.ts
  shared/src/common/interfaces/pages/index.ts
  shared/src/common/interfaces/pages/page-recent.interface.ts
  shared/src/common/interfaces/pages/page-statistic.interface.ts
  tests/specs/Infostack - API tests.postman_collection.json
Labels: enhancement

#354 fix: no notifications message
  frontend/src/components/common/with-header/components/header/components/nav-notification/nav-notification.tsx
Labels: bug

#382 Fix statistic shadow
  frontend/src/components/pages/components/chart/styles.module.scss
  frontend/src/components/pages/components/pages-statistic/pages-statistic.tsx
  frontend/src/components/pages/components/pages-statistic/styles.module.scss
Labels: bug

#387 New/breadcrumbs improvements
  frontend/src/components/pages/components/breadcrumbs/styles.module.scss
  frontend/src/components/pages/components/page-content/page-content.tsx
Labels: enhancement

#385 fix: landing layout
  landing/assets/img/example-1.png
  landing/assets/img/example-2.png
  landing/assets/img/example-3.png
  landing/assets/img/infostack.png
  landing/css/bootstrap.min.css
  landing/css/style.css
  landing/index.html
  landing/js/bootstrap.bundle.min.js
Labels: enhancement

#389 Fix/auth page input and button sizes
  frontend/src/components/auth/login/login.tsx
  frontend/src/components/auth/sign-up/sign-up.tsx
  frontend/src/components/auth/styles.module.scss
  frontend/src/components/common/form-field/form-field.tsx
  frontend/src/components/common/sign/sign.tsx
  frontend/src/components/pages/components/page-content/page-content.tsx
Labels: enhancement

#388 Fix: skill display in profile and settings
  backend/src/api/routes/user-route.ts
  backend/src/services/user.service.ts
  frontend/src/components/workspaces/workspaces.tsx
Labels: bug

#390 feat: added build and publish ability for mobile to generate apk and abp
  mobile/android/app/src/main/AndroidManifest.xml
  mobile/package.json
  mobile/src/common/constants/api.ts
  mobile/src/common/constants/index.ts
  mobile/src/components/workspaces/workspaces.tsx
  mobile/src/services/auth.service.ts
  mobile/src/services/http.service.ts
  mobile/src/services/page.service.ts
  mobile/src/services/workspace.service.ts
Labels: enhancement

#391 Fix statistic
  backend/src/common/mappers/page/map-recent-pages.helper.ts
  frontend/src/components/common/with-header/components/toolbar/toolbar.tsx
  frontend/src/components/common/with-header/with-header.tsx
  frontend/src/components/pages/components/chart/chart.tsx
  frontend/src/components/pages/components/pages-statistic/pages-statistic.tsx
  frontend/src/components/pages/components/pages-statistic/styles.module.scss
  frontend/src/components/pages/pages.tsx
Labels: bug

#392 Fix: multiple errors on invite accept
  backend/src/services/page.service.ts
Labels: bug

#386 fix: show comment to content with formatting
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/helpers/dom/dom.ts
  frontend/src/helpers/dom/get-parent-tags-with-skipping/get-parent-tags-with-skipping.helper.ts
  frontend/src/helpers/helpers.ts
Labels: bug

#393 Fix: no permission message replaced with 404 page for profiles
  frontend/src/components/profile-info/profile-info.tsx
Labels: bug

#399 Fix/toolbar titles size logo size
  frontend/src/components/common/with-header/components/header/components/nav-notification/styles.module.scss
  frontend/src/components/common/with-header/components/toolbar/components/page-item/page-item.tsx
  frontend/src/components/common/with-header/components/toolbar/styles.module.scss
  frontend/src/components/pages/components/content-editor/styles.module.scss
Labels: bug

#398 fix: clickable buttons in audio comment
  frontend/src/components/pages/components/comment-section/components/record-modal/record-modal.tsx
  frontend/src/components/pages/components/comment-section/components/record-modal/styles.module.scss
Labels: bug

#400 fix: change selected workspace back button
  frontend/src/components/settings/components/skill-settings/components/skill-item/skill-item.tsx
  frontend/src/components/settings/components/tag-settings/components/tag-item/tag-item.tsx
  frontend/src/components/workspaces/styles.module.scss
  frontend/src/components/workspaces/workspaces.tsx
Labels: bug

#402 Fix/settings avatar height
  frontend/src/components/settings/components/profile-settings/styles.module.scss
Labels: bug

#403 Fix: paddings in profile
  frontend/src/components/profile-info/profile-info.scss
Labels: bug

#404 fix: integration settings padding
  frontend/src/components/settings/components/integration-settings/styles.module.scss
Labels: bug

#406 Fix/audio comment rec modal buttons
  frontend/src/components/pages/components/comment-section/components/record-modal/record-modal.tsx
  frontend/src/components/pages/components/comment-section/components/record-modal/styles.module.scss
Labels: bug

#412 fix: change All/Me button in profile
  frontend/src/components/profile-info/components/activities/activities.tsx
  frontend/src/components/profile-info/components/activities/styles.module.scss
Labels: bug

#409 Fix: currentWorkspace removal on user deletion
  frontend/src/components/main/main.tsx
Labels: bug

#410 Fix: pinned pages remain after user deletion from workspace
  backend/src/data/repositories/page.repository.ts
  backend/src/services/workspace.service.ts
Labels: bug

#413 fix: permissions bug
  backend/src/services/page.service.ts
Labels: bug

#414 fix: invite form window increased
  frontend/src/components/auth/sign-up-invite/sign-up-invite.tsx
Labels: bug

#417 New/presentation seeds
  backend/package-lock.json
  backend/package.json
  backend/src/common/types/page-content.type.ts
  backend/src/common/utils/create-page-content.util.ts
  backend/src/common/utils/get-random-from-array.util.ts
  backend/src/common/utils/index.ts
  backend/src/data/seed-data/page-content.data.ts
  backend/src/data/seed-data/page-contents/api-reference/api-reference.content.ts
  backend/src/data/seed-data/page-contents/api-reference/index.ts
  backend/src/data/seed-data/page-contents/api-reference/other/create-selector.content.ts
  backend/src/data/seed-data/page-contents/api-reference/other/index.ts
  backend/src/data/seed-data/page-contents/api-reference/other/mathcing-utilities.content.ts
  backend/src/data/seed-data/page-contents/api-reference/other/other-exports.content.ts
  backend/src/data/seed-data/page-contents/api-reference/other/other.content.ts
  backend/src/data/seed-data/page-contents/api-reference/reducers-and-actions/create-action.content.ts
  backend/src/data/seed-data/page-contents/api-reference/reducers-and-actions/create-async-thunk.content.ts
  backend/src/data/seed-data/page-contents/api-reference/reducers-and-actions/create-entity-adapter.content.ts
  backend/src/data/seed-data/page-contents/api-reference/reducers-and-actions/create-reducer.content.ts
  backend/src/data/seed-data/page-contents/api-reference/reducers-and-actions/create-slice.content.ts
  backend/src/data/seed-data/page-contents/api-reference/reducers-and-actions/index.ts
  backend/src/data/seed-data/page-contents/api-reference/reducers-and-actions/reducers-and-actions.content.ts
  backend/src/data/seed-data/page-contents/api-reference/store-setup/configure-store.content.ts
  backend/src/data/seed-data/page-contents/api-reference/store-setup/get-default-middleware.content.ts
  backend/src/data/seed-data/page-contents/api-reference/store-setup/immutability-middleware.content.ts
  backend/src/data/seed-data/page-contents/api-reference/store-setup/index.ts
  backend/src/data/seed-data/page-contents/api-reference/store-setup/serializability-middleware.content.ts
  backend/src/data/seed-data/page-contents/api-reference/store-setup/store-setup.content.ts
  backend/src/data/seed-data/page-contents/index.ts
  backend/src/data/seed-data/page-contents/introduction/getting-started.ts
  backend/src/data/seed-data/page-contents/introduction/index.ts
  backend/src/data/seed-data/page-contents/tutorials/index.ts
  backend/src/data/seed-data/page-contents/tutorials/query-quick-start.ts
  backend/src/data/seed-data/page-contents/tutorials/quick-start.ts
  backend/src/data/seed-data/page-contents/tutorials/tutorials.ts
  backend/src/data/seed-data/page-contents/tutorials/typescript-quick-start.ts
  backend/src/data/seed-data/page-contents/usage/index.ts
  backend/src/data/seed-data/page-contents/usage/usage-guide.ts
  backend/src/data/seed-data/page-contents/usage/usage-with-typescript.ts
  backend/src/data/seed-data/page-contents/usage/writing-reducers-with-immer.ts
  backend/src/data/seed-data/page.data.ts
  backend/src/data/seed-data/pages/api.ts
  backend/src/data/seed-data/pages/getting-started.ts
  backend/src/data/seed-data/pages/index.ts
  backend/src/data/seed-data/pages/page.type.ts
  backend/src/data/seed-data/pages/tutorials.ts
  backend/src/data/seed-data/pages/usage.ts
  backend/src/data/seed-data/user-workspace.data.ts
  backend/src/data/seed-data/user.data.ts
  backend/src/data/seed-data/users/index.ts
  backend/src/data/seed-data/users/users.ts
  backend/src/data/seed-data/workspace.data.ts
  frontend/src/components/pages/components/page-content/page-content.tsx
  package.json
Labels: enhancement

#418 fix: contributors card wrap avatars
  backend/package.json
  frontend/src/components/pages/components/page-contributors/page-contributors.tsx
Labels: bug

#420 Fix/page version dropdown spacing and avatar shadow
  frontend/src/components/common/with-header/components/header/components/nav-profile/styles.scss
  frontend/src/components/pages/components/version-dropdown/styles.module.scss
  frontend/src/components/pages/components/version-dropdown/version-dropdown.tsx
  frontend/src/components/pages/components/version-item/styles.module.scss
  frontend/src/components/profile-info/components/activities/activities.tsx
  frontend/src/components/profile-info/components/activities/styles.module.scss
Labels: bug

#421 fix notification block
  frontend/src/components/common/with-header/components/header/components/nav-notification/nav-notification.tsx
  frontend/src/components/common/with-header/components/header/components/nav-notification/styles.module.scss
Labels: bug

#416 fix: change avatar link in profile (activities)
  frontend/src/components/profile-info/components/activities/activities.tsx
  frontend/src/components/profile-info/components/activities/styles.module.scss
Labels: bug

#422 fix: add following users avatars wrap
  frontend/src/components/pages/components/page-following-users/page-following-users.tsx
Labels: bug

#423 fix: add team settings avatar link
  frontend/src/components/settings/components/team-settings/components/item/item.tsx
  frontend/src/components/settings/components/team-settings/components/item/styles.module.scss
Labels: bug

#424 fix: add elasticsearch to readme
  readme.md
Labels: documentation
