Repository BinaryStudioAcademy/bsa-2021-infostack, pull requests merged in 2021-08, with the labels that each got.

#11 feat: implement workspace settings page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/enums/app/app-route.enum.ts
  frontend/src/components/app/app.tsx
  frontend/src/components/workspace/integration-settings/integration-settings.tsx
  frontend/src/components/workspace/profile-settings/profile-settings.tsx
  frontend/src/components/workspace/styles.scss
  frontend/src/components/workspace/tag-settings/tag-settings.tsx
  frontend/src/components/workspace/team-settings/team-settings.tsx
  frontend/src/components/workspace/users-settings/users-settings.tsx
  frontend/src/components/workspace/workspace.tsx
  frontend/src/index.tsx
  package-lock.json
Labels: enhancement

#15 fix: cleaned up the front end
  frontend/src/components/app/app.tsx
  frontend/src/components/counter/counter.tsx
  frontend/src/components/counter/styles.module.scss
  frontend/src/index.tsx
  frontend/src/store/actions.ts
  frontend/src/store/counter/actions.ts
  frontend/src/store/counter/common.ts
  frontend/src/store/counter/index.ts
  frontend/src/store/counter/slice.ts
  frontend/src/store/root-reducer.ts
Labels: enhancement

#13 feat: add an ability to manage user profile in settings
  .ls-lint.yml
  backend/.env.example
  backend/package-lock.json
  backend/package.json
  backend/src/api/routes/user-route.ts
  backend/src/common/helpers/multer.helper.ts
  backend/src/common/helpers/s3-file-storage.helper.ts
  backend/src/data/entities/user.ts
  backend/src/data/migrations/.gitkeep
  backend/src/data/migrations/1627557841360-add-tables.ts
  backend/src/data/migrations/1627897596559-update-user-add-avatar-column.ts
  backend/src/data/seed-data/user.data.ts
  backend/src/env.ts
  backend/src/services/auth.service.ts
  backend/src/services/user.service.ts
  frontend/package.json
  frontend/src/assets/css/styles.scss
  frontend/src/assets/img/logo.svg
  frontend/src/components/profile/components/profile-edit/.gitkeep
  frontend/src/components/profile/components/profile-edit/profile-edit.module.scss
  frontend/src/components/profile/components/profile-edit/profile-edit.tsx
  frontend/src/components/profile/profile.module.scss
  frontend/src/components/profile/profile.tsx
  frontend/src/services/auth-api/auth-api.service.ts
  frontend/src/services/user-api/.gitkeep
  frontend/src/services/user-api/user-api.service.ts
  frontend/src/store/auth/actions.ts
  shared/src/common/enums/http/http-method.enum.ts
  shared/src/common/interfaces/user/user.interface.ts
Labels: enhancement

#17 fix: cannot open specific page using direct link
  backend/src/server.ts
Labels: bug

#18 fix: auth middleware correctly uses secret key
  backend/src/api/middlewares/authorization-middleware.ts
Labels: enhancement

#21 fix: syles are broken
  frontend/src/assets/css/styles.scss
  frontend/src/components/app/app.tsx
  frontend/src/components/common/form-field/styles.module.scss
  frontend/src/components/header/components/nav-profile.tsx
  frontend/src/components/header/header.scss
  frontend/src/components/profile/components/profile-edit/profile-edit.module.scss
  frontend/src/components/profile/profile.module.scss
Labels: bug

#7 Added ability to choose workspace
  backend/package-lock.json
  backend/package.json
  backend/src/api/middlewares/authorization-middleware.ts
  backend/src/api/routes/index.ts
  backend/src/api/routes/workspace-route.ts
  backend/src/common/helpers/route.helper.ts
  backend/src/data/repositories/page-repository.ts
  backend/src/data/repositories/team.repository.ts
  backend/src/data/repositories/user-workspace.repository.ts
  backend/src/data/repositories/user.repository.ts
  backend/src/data/repositories/workspace.repository.ts
  backend/src/services/workspace.service.ts
  frontend/src/common/enums/app/reducer-name.enum.ts
  frontend/src/common/enums/cookies/cookies.ts
  frontend/src/common/enums/enums.ts
  frontend/src/common/enums/local-starage/local-storage.ts
  frontend/src/common/interfaces/components/button/index.ts
  frontend/src/common/interfaces/workspace/index.ts
  frontend/src/components/common/protected-route/protected-route.tsx
  frontend/src/components/header/header.scss
  frontend/src/components/login/login.tsx
  frontend/src/components/workspaces/components/create-workspace-button/create-workspace-button.tsx
  frontend/src/components/workspaces/components/create-workspace-button/styles.scss
  frontend/src/components/workspaces/components/create-workspace-popup/create-workspace-popup.tsx
  frontend/src/components/workspaces/components/workspace-item/styles.scss
  frontend/src/components/workspaces/components/workspace-item/workspace-item.tsx
  frontend/src/components/workspaces/styles.scss
  frontend/src/components/workspaces/workspaces.tsx
  frontend/src/helpers/dom/dom.ts
  frontend/src/helpers/dom/focus-on-elements/focus-on-input.ts
  frontend/src/hooks/hooks.ts
  frontend/src/index.tsx
  frontend/src/services/auth-api/auth-api.service.ts
  frontend/src/services/http/http.service.ts
  frontend/src/services/index.ts
  frontend/src/services/workspace-api/.gitkeep
  frontend/src/services/workspace-api/workspace-api.service.ts
  frontend/src/store/actions.ts
  frontend/src/store/root-reducer.ts
  frontend/src/store/workspaces/actions.ts
  frontend/src/store/workspaces/common.ts
  frontend/src/store/workspaces/index.ts
  frontend/src/store/workspaces/slice.ts
  shared/src/common/enums/cookies/cookie-variable.ts
  shared/src/common/enums/cookies/index.ts
  shared/src/common/enums/http/http-header.enum.ts
  shared/src/common/enums/index.ts
  shared/src/common/enums/local-storage/index.ts
  shared/src/common/enums/local-storage/local-storage-variable.ts
  shared/src/common/interfaces/index.ts
  shared/src/common/interfaces/workspace/.gitkeep
  shared/src/common/interfaces/workspace/index.ts
  shared/src/common/interfaces/workspace/workspace-creation.interface.ts
  shared/src/common/interfaces/workspace/workspace.interface.ts
Labels: enhancement

#16 New/view workspace users
  backend/src/api/middlewares/permissions-middleware.ts
  backend/src/api/routes/index.ts
  backend/src/api/routes/workspace-route.ts
  backend/src/common/interfaces/workspace/workspace-user.ts
  backend/src/common/mappers/workspace/map-workspace-to-workspace-users.ts
  backend/src/config/ormconfig.ts
  backend/src/data/entities/enums/permission-option.ts
  backend/src/data/entities/enums/user-role.ts
  backend/src/data/entities/team-permission.ts
  backend/src/data/entities/user-permission.ts
  backend/src/data/entities/user-workspace.ts
  backend/src/data/repositories/workspace.repository.ts
  backend/src/data/seeders.ts
  backend/src/data/seeders/team-permission.seeder.ts
  backend/src/data/seeders/user-workspace.seeder.ts
  backend/src/services/workspace.service.ts
  frontend/.env.example
  frontend/src/common/enums/app/reducer-name.enum.ts
  frontend/src/common/interfaces/workspace/index.ts
  frontend/src/components/workspace/styles.scss
  frontend/src/components/workspace/users-settings/add-user/add-user.tsx
  frontend/src/components/workspace/users-settings/styles.module.scss
  frontend/src/components/workspace/users-settings/table-head/table-head.tsx
  frontend/src/components/workspace/users-settings/user-item/add-team/add-team.tsx
  frontend/src/components/workspace/users-settings/user-item/teams/teams.tsx
  frontend/src/components/workspace/users-settings/user-item/user-item.tsx
  frontend/src/components/workspace/users-settings/users-settings.tsx
  frontend/src/components/workspace/workspace.tsx
  frontend/src/services/workspace-api/workspace-api.service.ts
  frontend/src/store/root-reducer.ts
  frontend/src/store/workspace/actions.ts
  frontend/src/store/workspace/common.ts
  frontend/src/store/workspace/index.ts
  frontend/src/store/workspace/slice.ts
  shared/src/common/enums/permissions/permission-type.enum.ts
  shared/src/common/enums/roles/role-type.enum.ts
  shared/src/common/interfaces/index.ts
  shared/src/common/interfaces/workspace/index.ts
  shared/src/common/interfaces/workspace/workspace-user.interface.ts
Labels: enhancement

#19 Fix/login signup
  frontend/src/components/common/form-field/form-field.tsx
  frontend/src/components/common/sign/sign.tsx
  frontend/src/components/login/login.tsx
  frontend/src/components/sign-up/sign-up.tsx
  frontend/src/helpers/boolean/boolean.ts
  frontend/src/helpers/helpers.ts
  shared/src/helpers/boolean/contains-no-empty-strings/contains-no-empty-strings.helper.ts
  shared/src/helpers/index.ts
Labels: enhancement

#20 Added ability to display user in header
  backend/src/api/routes/user-route.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/app/app.tsx
  frontend/src/components/common/protected-route/protected-route.tsx
  frontend/src/components/header/components/nav-notification/nav-notification.tsx
  frontend/src/components/header/components/nav-profile.tsx
  frontend/src/components/header/components/nav-profile/nav-profile.tsx
  frontend/src/components/header/components/nav-profile/styles.scss
  frontend/src/components/header/components/search/search.tsx
  frontend/src/components/header/header.tsx
  frontend/src/components/header/styles.scss
  frontend/src/components/profile/components/profile-edit/profile-edit.tsx
  frontend/src/services/auth-api/auth-api.service.ts
  frontend/src/services/index.ts
  frontend/src/services/user-api/user-api.service.ts
  frontend/src/store/auth/actions.ts
Labels: enhancement

#23 fix: update user 503 error
  backend/package-lock.json
  backend/src/common/helpers/multer.helper.ts
  frontend/src/components/header/components/nav-profile/nav-profile.tsx
  frontend/src/components/profile/components/profile-edit/profile-edit.tsx
  frontend/src/components/profile/profile.tsx
Labels: bug

#27 Fix/security middlewares
  backend/src/api/middlewares/permissions-middleware.ts
  frontend/src/components/workspaces/workspaces.tsx
  shared/src/common/enums/cookies/cookie-variable.ts
Labels: bug

#25 Fixed workspace selection after sign up
  frontend/src/components/app/app.tsx
  frontend/src/components/sign-up/sign-up.tsx
  frontend/src/components/workspaces/components/create-workspace-button/styles.scss
  frontend/src/components/workspaces/components/workspace-item/styles.scss
  frontend/src/components/workspaces/styles.scss
  frontend/src/components/workspaces/workspaces.tsx
Labels: bug

#29 fix: add routes and styles
  backend/src/common/helpers/s3-file-storage.helper.ts
  frontend/src/common/enums/app/app-route.enum.ts
  frontend/src/components/app/app.tsx
  frontend/src/components/header/components/nav-profile/nav-profile.tsx
  frontend/src/components/profile/profile.tsx
  frontend/src/components/settings/components/menu.module.scss
  frontend/src/components/settings/components/menu.tsx
  frontend/src/components/settings/settings.module.scss
  frontend/src/components/settings/settings.tsx
  frontend/src/services/http/http.service.ts
Labels: bug

#32 Fix workspaceId cookie path
  frontend/src/components/workspaces/workspaces.tsx
Labels: bug

#30 fix: update import paths
  frontend/src/components/profile/components/profile-edit/profile-edit.tsx
  frontend/src/components/settings/components/menu.tsx
  frontend/src/components/settings/settings.tsx
Labels: enhancement

#33 fix: workspaceId gets properly removed on logout
  frontend/src/components/header/components/nav-profile/nav-profile.tsx
Labels: bug

#34 feat: added profile with workspace validation
  backend/src/api/routes/user-route.ts
  backend/src/api/routes/workspace-route.ts
  backend/src/services/user.service.ts
  frontend/src/assets/img/user.svg
  frontend/src/common/enums/app/app-route.enum.ts
  frontend/src/components/app/app.tsx
  frontend/src/components/header/components/nav-profile/nav-profile.tsx
  frontend/src/components/header/header.tsx
  frontend/src/components/profile-info/.gitkeep
  frontend/src/components/profile-info/profile-info.scss
  frontend/src/components/profile-info/profile-info.tsx
  frontend/src/services/user-api/user-api.service.ts
Labels: enhancement

#31 New/toolbar
  backend/src/api/routes/index.ts
  backend/src/api/routes/page-route.ts
  backend/src/data/repositories/page-repository.ts
  backend/src/data/repositories/team-permission-repository.ts
  backend/src/data/repositories/user-permission.repository.ts
  backend/src/data/repositories/user.repository.ts
  backend/src/services/page.service.ts
  frontend/src/assets/css/styles.scss
  frontend/src/common/enums/app/reducer-name.enum.ts
  frontend/src/common/interfaces/page/index.ts
  frontend/src/components/app/app.tsx
  frontend/src/components/main/main.tsx
  frontend/src/components/main/styles.module.scss
  frontend/src/components/pages/components/toolbar/.gitkeep
  frontend/src/components/pages/pages.tsx
  frontend/src/components/toolbar/components/page-item/page-item.tsx
  frontend/src/components/toolbar/components/pages-list/pages-list.tsx
  frontend/src/components/toolbar/components/plus-button/plus-button.tsx
  frontend/src/components/toolbar/styles.module.scss
  frontend/src/components/toolbar/toolbar.tsx
  frontend/src/components/workspaces/workspaces.tsx
  frontend/src/services/index.ts
  frontend/src/services/page-api/page-api.service.ts
  frontend/src/store/actions.ts
  frontend/src/store/pages/actions.ts
  frontend/src/store/pages/common.ts
  frontend/src/store/pages/index.ts
  frontend/src/store/pages/slice.ts
  frontend/src/store/root-reducer.ts
  package-lock.json
  shared/package.json
  shared/src/common/interfaces/index.ts
  shared/src/common/interfaces/pages/index.ts
  shared/src/common/interfaces/pages/page-content.interface.ts
  shared/src/common/interfaces/pages/page.interface.ts
Labels: enhancement

#36 Feature/ability to create&view a page
  backend/package.json
  backend/src/api/middlewares/authorization-middleware.ts
  backend/src/api/routes/index.ts
  backend/src/api/routes/page-route.ts
  backend/src/common/helpers/route.helper.ts
  backend/src/common/interfaces/pages/index.ts
  backend/src/data/repositories/page-content.repository.ts
  backend/src/data/repositories/page.repository.ts
  backend/src/data/repositories/user-permissions.repository.ts
  backend/src/services/page.service.ts
  frontend/src/common/enums/app/reducer-name.enum.ts
  frontend/src/common/enums/local-storage/local-storage.ts
  frontend/src/common/interfaces/pages/index.ts
  frontend/src/components/app/app.tsx
  frontend/src/components/common/link/link.tsx
  frontend/src/components/pages/components/page-content/.gitkeep
  frontend/src/components/pages/components/page-content/page-content.scss
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/components/pages/pages.module.scss
  frontend/src/components/pages/pages.tsx
  frontend/src/components/toolbar/components/page-item/page-item.tsx
  frontend/src/components/toolbar/components/plus-button/plus-button.tsx
  frontend/src/components/toolbar/toolbar.tsx
  frontend/src/services/page-api/.gitkeep
  frontend/src/services/page-api/page-api.service.ts
  frontend/src/store/pages/.gitkeep
  frontend/src/store/pages/actions.ts
  frontend/src/store/pages/common.ts
  frontend/src/store/pages/slice.ts
  frontend/src/store/root-reducer.ts
  package-lock.json
  package.json
  shared/package.json
  shared/src/common/interfaces/index.ts
  shared/src/common/interfaces/pages/index.ts
  shared/src/common/interfaces/pages/page-content.interface.ts
  shared/src/common/interfaces/pages/page-request.interface.ts
  shared/src/common/interfaces/pages/page.interface.ts
Labels: enhancement

#43 Fix/profile style fixes, default avatar fixed
  frontend/src/assets/img/user.svg
  frontend/src/components/profile-info/profile-info.scss
  frontend/src/components/profile-info/profile-info.tsx
Labels: bug

#44 fix: avatar display correctly in profile settings
  frontend/src/components/profile/components/profile-edit/profile-edit.tsx
  frontend/src/components/profile/components/profile-edit/styles.module.scss
  frontend/src/components/settings/components/menu.tsx
  frontend/src/components/settings/components/styles.module.scss
  frontend/src/components/settings/settings.tsx
  frontend/src/components/settings/styles.module.scss
Labels: bug

#40 Feat/view users in settings
  backend/src/api/middlewares/permissions-middleware.ts
  backend/src/api/middlewares/verify-user-id.ts
  backend/src/api/middlewares/verify-workspace-id.ts
  backend/src/api/routes/workspace-route.ts
  backend/src/common/interfaces/workspace/workspace-creation.ts
  backend/src/common/interfaces/workspace/workspace-user-role.ts
  backend/src/common/interfaces/workspace/workspace.ts
  backend/src/data/repositories/page-content.repository.ts
  backend/src/data/repositories/page-repository.ts
  backend/src/data/repositories/page.repository.ts
  backend/src/data/repositories/team-permission.repository.ts
  backend/src/data/repositories/user-permission.repository.ts
  backend/src/data/repositories/user-permissions.repository.ts
  backend/src/data/repositories/user-workspace-repository.ts
  backend/src/data/repositories/user-workspace.repository.ts
  backend/src/data/seeders/team-permission.seeder.ts
  backend/src/services/page.service.ts
  backend/src/services/workspace.service.ts
  frontend/src/common/enums/app/app-route.enum.ts
  frontend/src/common/enums/enums.ts
  frontend/src/common/enums/roles/roles.ts
  frontend/src/common/interfaces/workspace/index.ts
  frontend/src/components/header/components/nav-profile/nav-profile.tsx
  frontend/src/components/settings/components/menu.tsx
  frontend/src/components/settings/settings.tsx
  frontend/src/components/workspace/users-settings/styles.module.scss
  frontend/src/components/workspace/users-settings/users-settings.tsx
  frontend/src/services/workspace-api/workspace-api.service.ts
  frontend/src/store/workspace/actions.ts
  shared/src/common/interfaces/workspace/index.ts
  shared/src/common/interfaces/workspace/workspace-user-role.interface.ts
Labels: enhancement

#46 Fix work with cookies
  frontend/src/components/main/main.tsx
  frontend/src/components/workspaces/workspaces.tsx
  frontend/src/store/workspaces/common.ts
  frontend/src/store/workspaces/slice.ts
Labels: bug

#50 Fix/reset password mailer login issue
  backend/.env.example
  backend/package-lock.json
  backend/package.json
  backend/src/common/utils/mailer.util.ts
  backend/src/env.ts
Labels: bug

#38 New/form validation
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/interfaces/auth/index.ts
  frontend/src/components/common/form-field/form-field.tsx
  frontend/src/components/login/login.tsx
  frontend/src/components/reset-password/reset-password.tsx
  frontend/src/components/set-password/set-password.tsx
  frontend/src/components/sign-up/sign-up.tsx
  frontend/src/hooks/hooks.ts
  frontend/src/validations/login-schema.ts
  frontend/src/validations/regex/regex.ts
  frontend/src/validations/reset-password-schema.ts
  frontend/src/validations/set-password-schema.ts
  frontend/src/validations/sign-up-schema.ts
  shared/src/common/interfaces/auth/index.ts
  shared/src/common/interfaces/auth/set-password-validation.interface.ts
Labels: enhancement

#51 fix: show users tab after page reload
  frontend/src/components/settings/components/menu.tsx
Labels: bug

#54 Fix/page title
  frontend/public/favicon.ico
  frontend/public/index.html
Labels: bug

#53 New/toolbar
  frontend/src/components/toolbar/components/page-item/page-item.tsx
  frontend/src/components/toolbar/components/plus-button/plus-button-root.tsx
  frontend/src/components/toolbar/components/plus-button/plus-button.tsx
  frontend/src/components/toolbar/styles.module.scss
  frontend/src/components/toolbar/toolbar.tsx
Labels: enhancement

#52 fix: implement smart caching for avatars
  frontend/src/components/header/components/nav-profile/styles.scss
  frontend/src/components/profile-info/profile-info.scss
  frontend/src/components/profile-info/profile-info.tsx
  frontend/src/components/profile/components/profile-edit/profile-edit.tsx
  shared/package.json
Labels: bug

#35 Added refresh token logic
  backend/src/api/middlewares/authorization-middleware.ts
  backend/src/api/routes/auth-route.ts
  backend/src/common/interfaces/auth/refresh-tokens.interface.ts
  backend/src/common/interfaces/auth/tokens.interface.ts
  backend/src/common/interfaces/user/user-auth.interface.ts
  backend/src/common/utils/generate-access-token.util.ts
  backend/src/common/utils/tokens.util.ts
  backend/src/config/jwt-config.ts
  backend/src/config/white-list-routes-config.ts
  backend/src/data/repositories/refresh-token.repository.ts
  backend/src/data/repositories/team-permission.repository.ts
  backend/src/data/repositories/user-permission.repository.ts
  backend/src/data/repositories/user-permissions.repository.ts
  backend/src/data/repositories/user-workspace.repository.ts
  backend/src/data/repositories/user.repository.ts
  backend/src/services/auth.service.ts
  frontend/src/common/interfaces/auth/index.ts
  frontend/src/components/app/app.tsx
  frontend/src/services/auth-api/auth-api.service.ts
  frontend/src/services/http/http.service.ts
  frontend/src/store/auth/actions.ts
  frontend/src/store/auth/common.ts
  frontend/src/store/auth/slice.ts
  frontend/src/store/workspaces/actions.ts
  shared/src/common/enums/http/http-error-message.enum.ts
  shared/src/common/enums/local-storage/local-storage-variable.ts
  shared/src/common/interfaces/auth/index.ts
  shared/src/common/interfaces/auth/refresh-tokens.interface.ts
  shared/src/common/interfaces/auth/tokens.interface.ts
Labels: enhancement

#59 Patch/seed data
  backend/src/data/repositories/tag.repository.ts
  backend/src/data/seed-data/comment.data.ts
  backend/src/data/seed-data/page-content.data.ts
  backend/src/data/seed-data/page-tag.data.ts
  backend/src/data/seed-data/page.data.ts
  backend/src/data/seed-data/tag.data.ts
  backend/src/data/seed-data/team-member.data.ts
  backend/src/data/seed-data/team-permission.data.ts
  backend/src/data/seed-data/team.data.ts
  backend/src/data/seed-data/user-permission.data.ts
  backend/src/data/seed-data/user-workspace.data.ts
  backend/src/data/seed-data/user.data.ts
  backend/src/data/seed-data/workspace.data.ts
  backend/src/data/seeders.ts
  backend/src/data/seeders/comment.seeder.ts
  backend/src/data/seeders/page-content.seeder.ts
  backend/src/data/seeders/page-tag.seeder.ts
  backend/src/data/seeders/tag.seeder.ts
  backend/src/data/seeders/user-permission.seeder.ts
Labels: enhancement

#60 Fix workspace creating
  backend/src/data/repositories/workspace.repository.ts
  backend/src/services/workspace.service.ts
  frontend/src/components/header/components/nav-profile/nav-profile.tsx
  frontend/src/components/main/main.tsx
  frontend/src/components/workspaces/components/create-workspace-button/styles.scss
  frontend/src/components/workspaces/components/create-workspace-popup/create-workspace-popup.tsx
  frontend/src/components/workspaces/components/create-workspace-popup/styles.scss
  frontend/src/components/workspaces/components/workspace-item/workspace-item.tsx
  frontend/src/components/workspaces/styles.scss
  frontend/src/components/workspaces/workspaces.tsx
  frontend/src/store/workspaces/actions.ts
  frontend/src/store/workspaces/common.ts
  frontend/src/store/workspaces/slice.ts
  shared/src/common/enums/http/http-error-message.enum.ts
Labels: bug

#58 Fix/bumb ts node dev
  backend/package-lock.json
  backend/package.json
Labels: enhancement

#61 Fix/worksapce design
  frontend/src/components/workspaces/components/container/container.tsx
  frontend/src/components/workspaces/components/container/styles.module.scss
  frontend/src/components/workspaces/components/create-button/create-button.tsx
  frontend/src/components/workspaces/components/create-workspace-button/create-workspace-button.tsx
  frontend/src/components/workspaces/components/create-workspace-button/styles.scss
  frontend/src/components/workspaces/components/create-workspace-popup/create-workspace-popup.tsx
  frontend/src/components/workspaces/components/create-workspace-popup/styles.scss
  frontend/src/components/workspaces/components/index.ts
  frontend/src/components/workspaces/components/item/item.tsx
  frontend/src/components/workspaces/components/popup/popup.tsx
  frontend/src/components/workspaces/components/spinner/spinner.tsx
  frontend/src/components/workspaces/components/workspace-item/styles.scss
  frontend/src/components/workspaces/components/workspace-item/workspace-item.tsx
  frontend/src/components/workspaces/styles.scss
  frontend/src/components/workspaces/workspaces.tsx
Labels: enhancement

#68 Fix profile styles
  frontend/src/components/profile-info/profile-info.scss
  frontend/src/components/profile-info/profile-info.tsx
Labels: bug

#69 Fix settings styles
  frontend/src/components/profile-info/.gitkeep
  frontend/src/components/profile-info/profile-info.scss
  frontend/src/components/profile/components/profile-edit/profile-edit.tsx
  frontend/src/components/profile/components/profile-edit/styles.module.scss
  frontend/src/components/settings/components/menu.tsx
  frontend/src/components/settings/components/styles.module.scss
  frontend/src/components/settings/settings.tsx
  frontend/src/components/settings/styles.module.scss
  frontend/src/components/workspace/users-settings/styles.module.scss
Labels: bug

#67 Fix text overflow
  frontend/src/components/header/components/nav-profile/nav-profile.tsx
  frontend/src/components/header/components/nav-profile/styles.scss
  frontend/src/components/workspaces/components/item/item.tsx
  frontend/src/components/workspaces/components/item/styles.module.scss
Labels: bug

#70 Fix workspace selection
  frontend/src/common/interfaces/components/button/index.ts
  frontend/src/components/workspaces/components/create-button/create-button.tsx
  frontend/src/components/workspaces/components/create-button/styles.module.scss
  frontend/src/components/workspaces/components/item/item.tsx
  frontend/src/components/workspaces/components/popup/popup.tsx
  frontend/src/components/workspaces/components/popup/styles.module.scss
  frontend/src/components/workspaces/workspaces.tsx
Labels: bug

#71 Fix page icon
  frontend/src/components/profile-info/profile-info.scss
  frontend/src/components/profile-info/profile-info.tsx
Labels: bug

#72 Fix text overflow
  frontend/src/components/workspace/users-settings/styles.module.scss
Labels: bug

#73 Fix/page is reloading when click on the same page in page list
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/components/toolbar/components/page-item/page-item.tsx
  frontend/src/components/toolbar/components/pages-list/pages-list.tsx
Labels: bug

#66 fix: add body bg color
  frontend/src/assets/css/styles.scss
Labels: bug

#65 fix: button styles and alignment
  frontend/src/components/profile/components/profile-edit/profile-edit.tsx
  frontend/src/components/profile/components/profile-edit/styles.module.scss
Labels: bug

#77 Fix refresh tokens
  frontend/src/common/enums/emitter/emitter-events.ts
  frontend/src/common/enums/emitter/emitter.ts
  frontend/src/common/enums/enums.ts
  frontend/src/components/profile-info/profile-info.tsx
  frontend/src/services/auth-api/auth-api.service.ts
  frontend/src/services/http/http.service.ts
  frontend/src/services/page-api/page-api.service.ts
  frontend/src/services/user-api/user-api.service.ts
  frontend/src/services/workspace-api/workspace-api.service.ts
  frontend/src/store/pages/actions.ts
Labels: bug

#76 Change routing for pages -> add enhancement & fix reloading same page
  backend/src/services/page.service.ts
  frontend/src/components/common/link/link.tsx
  frontend/src/components/toolbar/components/page-item/page-item.tsx
  frontend/src/components/toolbar/styles.module.scss
  frontend/src/components/toolbar/toolbar.tsx
  frontend/src/store/pages/actions.ts
  frontend/src/store/pages/slice.ts
Labels: bug, enhancement

#74 fix: changed the design of profile dropdown
  frontend/src/components/header/components/nav-profile/components/profile-item/profile-item.tsx
  frontend/src/components/header/components/nav-profile/components/profile-item/styles.module.scss
  frontend/src/components/header/components/nav-profile/nav-profile.tsx
Labels: enhancement

#64 fix: change s3 storing logic
  backend/src/common/helpers/multer.helper.ts
  backend/src/common/helpers/s3-file-storage.helper.ts
  backend/src/services/user.service.ts
  frontend/src/components/profile-info/profile-info.tsx
  frontend/src/components/profile/components/profile-edit/profile-edit.tsx
  frontend/src/services/http/http.service.ts
  frontend/src/services/user-api/user-api.service.ts
Labels: bug

#85 Fix/seed improvement
  backend/src/common/mappers/.gitkeep
  backend/src/data/seed-data/page-content.data.ts
  backend/src/data/seed-data/user-permission.data.ts
  backend/src/data/seeders/page.seeder.ts
Labels: enhancement

#87 fix: settings alignment
  frontend/src/components/profile/components/profile-edit/profile-edit.tsx
  frontend/src/components/profile/components/profile-edit/styles.module.scss
Labels: bug

#94 fix: return teams which belongs to workspace
  backend/src/common/mappers/workspace/map-workspace-to-workspace-users.ts
Labels: bug

#90 Feat: show contributors & fix mulptiple page reload after F5
  backend/src/api/routes/page-route.ts
  backend/src/common/interfaces/page/index.ts
  backend/src/common/mappers/page/map-page-contents-to-contributors.ts
  backend/src/data/repositories/page.repository.ts
  backend/src/data/seed-data/page-content.data.ts
  backend/src/data/seed-data/user-permission.data.ts
  backend/src/data/seed-data/user-workspace.data.ts
  backend/src/data/seed-data/user.data.ts
  backend/src/services/page.service.ts
  frontend/src/common/interfaces/pages/index.ts
  frontend/src/components/header/components/nav-profile/nav-profile.tsx
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/components/pages/components/page-contributors/page-contributors.tsx
  frontend/src/components/pages/components/page-contributors/styles.module.scss
  frontend/src/components/toolbar/components/page-item/page-item.tsx
  frontend/src/components/toolbar/toolbar.tsx
  frontend/src/helpers/helpers.ts
  frontend/src/helpers/route/route.ts
  frontend/src/services/page-api/page-api.service.ts
  shared/src/common/interfaces/pages/index.ts
  shared/src/common/interfaces/pages/page-contributor.interface.ts
Labels: enhancement

#95 feat: edit page content
  backend/src/api/middlewares/socket-middleware.ts
  backend/src/api/routes/page-route.ts
  backend/src/common/helpers/route.helper.ts
  backend/src/common/interfaces/page/index.ts
  backend/src/common/mappers/comment/map-child-to-parent.ts
  backend/src/data/repositories/page-content.repository.ts
  backend/src/data/repositories/page.repository.ts
  backend/src/data/repositories/user.repository.ts
  backend/src/services/comment.service.ts
  backend/src/services/page.service.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/enums/app/app-route.enum.ts
  frontend/src/common/interfaces/comment/index.ts
  frontend/src/common/interfaces/pages/index.ts
  frontend/src/components/common/spinner/spinner.tsx
  frontend/src/components/main/main.tsx
  frontend/src/components/pages/components/content-editor/content-editor.tsx
  frontend/src/components/pages/components/edit-button/edit-button.tsx
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/components/pages/pages.tsx
  frontend/src/components/profile-info/profile-info.tsx
  frontend/src/services/comment-api/comment-api.service.ts
  frontend/src/services/page-api/page-api.service.ts
  frontend/src/store/comments/actions.ts
  frontend/src/store/comments/slice.ts
  frontend/src/store/pages/actions.ts
  frontend/src/store/pages/common.ts
  shared/src/common/interfaces/comment/comment-request.interface.ts
  shared/src/common/interfaces/comment/comment.interface.ts
  shared/src/common/interfaces/pages/edit-page-content.interface.ts
  shared/src/common/interfaces/pages/index.ts
Labels: enhancement

#100 fix: fixed page-content styles
  frontend/package-lock.json
  frontend/src/components/pages/components/edit-button/edit-button.tsx
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/components/pages/components/page-contributors/page-contributors.tsx
  frontend/src/store/pages/actions.ts
  frontend/src/store/pages/common.ts
  shared/src/common/interfaces/pages/edit-page-content.interface.ts
Labels: enhancement

#91 New/following pages
  .eslintrc.yml
  backend/src/api/routes/page-route.ts
  backend/src/common/interfaces/page/index.ts
  backend/src/common/mappers/page/map-page-to-ipage.ts
  backend/src/common/mappers/page/map-pages-to-pages-nav.ts
  backend/src/data/entities/page.ts
  backend/src/data/entities/user.ts
  backend/src/data/migrations/1628242667822-add-following-pages.ts
  backend/src/data/repositories/page.repository.ts
  backend/src/data/repositories/user.repository.ts
  backend/src/data/seed-data/user-following-pages.data.ts
  backend/src/data/seeders.ts
  backend/src/data/seeders/user-following-pages.seeder.ts
  backend/src/services/auth.service.ts
  backend/src/services/page.service.ts
  backend/src/services/user.service.ts
  frontend/src/common/interfaces/pages/index.ts
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/components/profile-info/profile-info.tsx
  frontend/src/components/profile/components/profile-edit/profile-edit.tsx
  frontend/src/services/page-api/page-api.service.ts
  frontend/src/services/user-api/user-api.service.ts
  frontend/src/store/pages/actions.ts
  frontend/src/store/pages/common.ts
  frontend/src/store/pages/slice.ts
  shared/src/common/interfaces/pages/index.ts
  shared/src/common/interfaces/pages/page-followed-interface.ts
  shared/src/common/interfaces/pages/page.interface.ts
  shared/src/common/interfaces/user/user.interface.ts
Labels: enhancement

#102 fix: tag creation
  backend/src/services/tag.service.ts
Labels: bug

#104 fix: team creation
  backend/src/api/routes/team-route.ts
  backend/src/services/team.service.ts
Labels: bug

#108 Fix/last version titles in followings list
  backend/src/data/repositories/user.repository.ts
Labels: bug

#111 Fix: fixed work break on page content
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/components/pages/components/page-content/styles.module.scss
Labels: bug

#110 fix: hide modal team creation
  backend/src/services/team.service.ts
  frontend/src/components/workspace/team-settings/drop-down/drop-down.tsx
  frontend/src/components/workspace/team-settings/popup/popup.tsx
  frontend/src/components/workspace/team-settings/team-settings.tsx
  frontend/src/validations/team-name-schema.ts
Labels: bug

#107 Fix/settings menu display after worspace creation
  backend/src/services/workspace.service.ts
  frontend/src/components/workspace/team-settings/create-button/create-button.tsx
  frontend/src/components/workspace/team-settings/create-button/styles.scss
  frontend/src/components/workspaces/workspaces.tsx
Labels: bug

#112 Fix: fixed page content editor break word
  frontend/src/components/pages/components/content-editor/content-editor.tsx
  frontend/src/components/pages/components/content-editor/styles.module.scss
Labels: bug

#113 Fix: fixed empty comments
  frontend/src/components/pages/components/comment-form/comment-form.tsx
Labels: bug

#117 Fix: fixed editor reload
  frontend/src/components/pages/components/content-editor/content-editor.tsx
Labels: bug

#118 Fix/page commentary
  backend/src/server.ts
  backend/src/services/page.service.ts
  frontend/src/components/pages/components/comment-form/comment-form.tsx
  frontend/src/components/pages/components/comment/comment.tsx
  frontend/src/store/comments/slice.ts
Labels: enhancement

#122 fix: fixed a mistake
  backend/src/server.ts
Labels: enhancement

#125 fix: content editor formatting
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/pages/components/content-editor/content-editor.tsx
  frontend/src/components/pages/components/page-content/page-content.tsx
Labels: bug

#128 Fix permissions
  frontend/src/components/pages/components/page-content/page-content.tsx
Labels: bug

#126 fix when long page title is shifted to another page title, also with …
  frontend/src/components/toolbar/components/page-item/page-item.tsx
  frontend/src/components/toolbar/toolbar.tsx
Labels: bug

#127 Fix current page title
  frontend/src/components/pages/components/page-content/page-content.tsx
Labels: bug

#129 Fix edit page
  backend/src/api/routes/page-route.ts
  backend/src/services/page.service.ts
Labels: bug

#130 fix: made socket same port as express
  backend/src/server.ts
  frontend/.env.example
  frontend/src/common/enums/app/env.enum.ts
  frontend/src/context/socket.ts
Labels: bug

#124 fix: workspace name validation
  frontend/src/components/common/popup/popup.tsx
  frontend/src/components/common/popup/styles.module.scss
  frontend/src/components/profile/components/profile-edit/profile-edit.tsx
  frontend/src/components/workspace/tag-settings/tag-add/tag-add.tsx
  frontend/src/components/workspace/tag-settings/tag-settings.tsx
  frontend/src/components/workspaces/workspaces.tsx
  frontend/src/validations/account-info-schema.ts
  frontend/src/validations/regex/regex.ts
  frontend/src/validations/sign-up-invite-schema.ts
  frontend/src/validations/sign-up-schema.ts
  frontend/src/validations/workspace-schema.ts
Labels: bug

#134 Feat: replaced all avatars with single custom avatar component, added tooltips
  frontend/src/components/common/avatar/avatar.tsx
  frontend/src/components/header/components/nav-profile/nav-profile.tsx
  frontend/src/components/header/components/nav-profile/styles.scss
  frontend/src/components/header/styles.scss
  frontend/src/components/pages/components/comment-form/comment-form.tsx
  frontend/src/components/pages/components/comment/comment.tsx
  frontend/src/components/pages/components/page-contributors/page-contributors.tsx
  frontend/src/components/pages/components/response/response.tsx
  frontend/src/components/profile/components/profile-edit/profile-edit.tsx
  frontend/src/components/profile/components/profile-info/profile-info.scss
  frontend/src/components/profile/components/profile-info/profile-info.tsx
  frontend/src/components/workspace/team-settings/item/item.tsx
Labels: enhancement

#135 New: replaced text with badges for teams and users in permission modal
  frontend/src/components/pages/components/popup/components/item/item.tsx
Labels: enhancement

#140 Fix services
  frontend/src/services/http/http.service.ts
  frontend/src/services/skill-api/skill-api.service.ts
  frontend/src/services/tag-api/tag-api.service.ts
  frontend/src/services/team-api/team-api.service.ts
Labels: bug

#139 Fix read permission
  backend/src/services/page.service.ts
Labels: bug

#138 New/follow child pages
  backend/src/api/routes/page-route.ts
  backend/src/data/repositories/page.repository.ts
  backend/src/services/page.service.ts
  frontend/src/assets/css/styles.scss
  frontend/src/common/types/react/child.type.ts
  frontend/src/common/types/react/index.ts
  frontend/src/common/types/types.ts
  frontend/src/components/common/modal/modal.tsx
  frontend/src/components/common/modal/styles.module.scss
  frontend/src/components/pages/components/follow-modal/follow-modal.tsx
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/services/page-api/page-api.service.ts
  frontend/src/store/pages/actions.ts
Labels: enhancement

#141 Fix workspace title
  frontend/src/components/toolbar/toolbar.tsx
  frontend/src/components/workspaces/components/container/container.tsx
  frontend/src/components/workspaces/components/invite-item/invite-item.tsx
  frontend/src/components/workspaces/components/invite-item/styles.module.scss
  frontend/src/components/workspaces/components/item/item.tsx
  frontend/src/components/workspaces/components/item/styles.module.scss
Labels: bug

#136 fix: edit team name second time
  frontend/src/components/workspace/team-settings/popup/popup.tsx
  frontend/src/components/workspace/team-settings/team-settings.tsx
Labels: bug

#143 Fix/delete team
  backend/src/data/repositories/team-permission.repository.ts
  backend/src/data/repositories/team.repository.ts
  backend/src/services/team.service.ts
  frontend/src/components/pages/components/popup/popup.tsx
  frontend/src/components/settings/components/team-settings/components/modal/modal.tsx
  frontend/src/components/settings/components/team-settings/team-settings.tsx
  frontend/src/services/index.ts
  frontend/src/services/team-api/team-api.service.ts
  frontend/src/store/teams/actions.ts
  frontend/src/store/teams/common.ts
  frontend/src/store/teams/slice.ts
Labels: bug

#137 fix: error after saving team name without editing
  backend/src/services/team.service.ts
Labels: bug

#147 fix: fixed modal text
  frontend/src/components/pages/components/follow-modal/follow-modal.tsx
Labels: enhancement

#149 fix: api method
  backend/src/api/routes/page-route.ts
Labels: bug

#153 feat: notify followingUsers about new comments
  backend/src/common/constants/constants.ts
  backend/src/common/constants/notification.ts
  backend/src/common/enums/entity-type.ts
  backend/src/data/entities/notification.ts
  backend/src/data/entities/user-workspace.ts
  backend/src/data/migrations/1629138247028-add-notifications.ts
  backend/src/data/migrations/1629140541040-add-notification.ts
  backend/src/data/migrations/1629145540635-add-nullable-body-notification.ts
  backend/src/data/repositories/comment.repository.ts
  backend/src/data/repositories/notification.repository.ts
  backend/src/data/seed-data/notification.data.ts
  backend/src/data/seed-data/user-following-pages.data.ts
  backend/src/data/seeders.ts
  backend/src/data/seeders/notification.seeder.ts
  backend/src/services/comment.service.ts
  shared/src/common/enums/entity-type/entity-type.enum.ts
  shared/src/common/enums/entity-type/index.ts
  shared/src/common/enums/index.ts
  shared/src/common/interfaces/comment/comment.interface.ts
Labels: enhancement

#148 Fix/server email validation
  backend/package-lock.json
  backend/package.json
  backend/src/api/middlewares/index.ts
  backend/src/api/middlewares/validation-middleware.ts
  backend/src/api/routes/auth-route.ts
  backend/src/common/validations/index.ts
  frontend/package-lock.json
  frontend/src/common/enums/app/index.ts
  frontend/src/common/enums/app/request-status.enum.ts
  frontend/src/common/validations/index.ts
  frontend/src/components/auth/login/login.tsx
  frontend/src/components/auth/reset-password/reset-password.tsx
  frontend/src/components/auth/set-password/set-password.tsx
  frontend/src/components/auth/sign-up-invite/sign-up-invite.tsx
  frontend/src/components/auth/sign-up/sign-up.tsx
  frontend/src/components/common/invite-modal/invite-modal.tsx
  frontend/src/components/settings/components/profile-settings/profile-settings.tsx
  frontend/src/components/settings/components/team-settings/components/modal/modal.tsx
  frontend/src/components/workspaces/components/modal/modal.tsx
  shared/package-lock.json
  shared/package.json
  shared/src/common/validations/account-info-schema.ts
  shared/src/common/validations/index.ts
  shared/src/common/validations/login-schema.ts
  shared/src/common/validations/regex/regex.ts
  shared/src/common/validations/reset-password-schema.ts
  shared/src/common/validations/set-password-schema.ts
  shared/src/common/validations/sign-up-invite-schema.ts
  shared/src/common/validations/sign-up-schema.ts
  shared/src/common/validations/team-name-schema.ts
  shared/src/common/validations/workspace-schema.ts
  shared/src/index.ts
Labels: enhancement

#151 Feat/delete users from user settings
  backend/src/api/routes/workspace-route.ts
  backend/src/data/migrations/1629195023370-added-deleted-status.ts
  backend/src/services/page.service.ts
  backend/src/services/workspace.service.ts
  frontend/src/components/common/common.ts
  frontend/src/components/common/confirm-modal/confirm-modal.tsx
  frontend/src/components/common/delete-user-modal/delete-user-modal.tsx
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/components/pages/components/popup/popup.tsx
  frontend/src/components/settings/components/users-settings/components/user-item/user-item.tsx
  frontend/src/components/settings/components/users-settings/users-settings.tsx
  frontend/src/services/page-api/page-api.service.ts
  frontend/src/services/workspace-api/workspace-api.service.ts
  shared/src/common/enums/status/invite-status.enum.ts
Labels: enhancement

#156 made user unable to invite themselves
  frontend/src/components/common/invite-modal/invite-modal.tsx
Labels: bug

#158 Fix: fixed followings display in profile
  backend/src/services/user.service.ts
Labels: bug

#159 feat: add ability to unfollow page from profile
  frontend/src/components/profile-info/profile-info.scss
  frontend/src/components/profile-info/profile-info.tsx
Labels: enhancement

#160 Fix/title length over 50 symbols error. Page content could be empty on save now. Title could not be empty on save
  frontend/src/common/enums/enums.ts
  frontend/src/common/enums/page-content/page-title.ts
  frontend/src/components/pages/components/content-editor/content-editor.tsx
  frontend/src/components/pages/components/page-content/page-content.tsx
  shared/src/common/enums/index.ts
  shared/src/common/enums/page-content/index.ts
  shared/src/common/enums/page-content/page-title.enum.ts
Labels: bug

#165 Fix creating skills
  frontend/src/components/settings/components/profile-settings/profile-settings.tsx
Labels: bug

#161 Fix: duplicate invitations issue
  backend/src/common/mappers/workspace/map-workspace-to-workspace-users.ts
  frontend/src/components/common/invite-modal/invite-modal.tsx
  shared/src/common/interfaces/workspace/workspace-user.interface.ts
Labels: bug

#167 Fix: padding for ordered list in editor
  frontend/src/components/pages/components/content-editor/styles.module.scss
Labels: bug

#166 New/add pictures screenshots to the edit page
  backend/src/server.ts
  frontend/src/components/pages/components/content-editor/content-editor.tsx
  frontend/src/components/pages/components/content-editor/styles.module.scss
Labels: enhancement

#169 Fix: issue with following child pages when some are already followed
  backend/src/services/page.service.ts
  frontend/src/components/common/modal/modal.tsx
Labels: bug

#170 Fix permissions of deleted user
  backend/src/services/page.service.ts
  frontend/src/components/common/with-header/components/toolbar/components/page-item/page-item.tsx
  frontend/src/components/common/with-header/components/toolbar/toolbar.tsx
  frontend/src/store/pages/actions.ts
  frontend/src/store/pages/slice.ts
  shared/src/common/enums/http/http-error-message.enum.ts
Labels: bug

#172 fix: the user is not made Contributor after he edited a title of page
  frontend/src/components/pages/components/content-editor/content-editor.tsx
Labels: bug

#173 Fix page admin permissions
  frontend/src/components/common/common.ts
  frontend/src/components/pages/components/popup/components/components.ts
  frontend/src/components/pages/components/popup/components/delete-participant-modal/delete-participant-modal.tsx
  frontend/src/components/pages/components/popup/components/item/item.tsx
  frontend/src/components/pages/components/popup/popup.tsx
  frontend/src/components/settings/components/users-settings/components/components.ts
  frontend/src/components/settings/components/users-settings/components/delete-user-modal/delete-user-modal.tsx
  frontend/src/components/settings/components/users-settings/users-settings.tsx
Labels: bug

#176 fix/deleting the admin of the page
  frontend/src/components/settings/components/team-settings/components/popup-invite/popup-invite.tsx
Labels: bug

#180 Fix/table of content styles
  frontend/src/components/pages/components/page-table-of-contents/page-table-of-contents.tsx
  frontend/src/components/pages/components/page-table-of-contents/styles.module.scss
Labels: bug

#168 New/show activities
  backend/src/api/routes/user-route.ts
  backend/src/common/interfaces/common/index.ts
  backend/src/common/interfaces/user/index.ts
  backend/src/common/interfaces/user/user-activity-raw-result.interface.ts
  backend/src/common/mappers/user/map-user-activities-raw-results-to-user-activities.ts
  backend/src/data/repositories/activity.repository.ts
  backend/src/services/user.service.ts
  frontend/src/common/enums/app/reducer-name.enum.ts
  frontend/src/common/interfaces/common/index.ts
  frontend/src/common/interfaces/user/index.ts
  frontend/src/components/profile-info/components/activities/activities.tsx
  frontend/src/components/profile-info/components/activities/styles.module.scss
  frontend/src/components/profile-info/components/components.ts
  frontend/src/components/profile-info/profile-info.scss
  frontend/src/components/profile-info/profile-info.tsx
  frontend/src/services/user-api/user-api.service.ts
  frontend/src/store/actions.ts
  frontend/src/store/activities/actions.ts
  frontend/src/store/activities/common.ts
  frontend/src/store/activities/index.ts
  frontend/src/store/activities/slice.ts
  frontend/src/store/root-reducer.ts
  shared/src/common/interfaces/common/index.ts
  shared/src/common/interfaces/common/paginated.interface.ts
  shared/src/common/interfaces/common/pagination.interface.ts
  shared/src/common/interfaces/index.ts
  shared/src/common/interfaces/user/get-activities.interface.ts
  shared/src/common/interfaces/user/get-user-activities.interface.ts
  shared/src/common/interfaces/user/index.ts
  shared/src/common/interfaces/user/user-activity.interface.ts
Labels: enhancement

#177 Fix workspace admin permissions
  backend/src/data/repositories/user-workspace.repository.ts
  backend/src/services/page.service.ts
Labels: bug

#181 fix/ update pageTags permissions
  frontend/src/components/pages/components/page-tags/page-tags.tsx
Labels: bug

#183 Fix: user stays in teams after deletion from workspace
  backend/src/data/repositories/team.repository.ts
  backend/src/data/repositories/user.repository.ts
  backend/src/services/workspace.service.ts
Labels: bug

#185 fix: change delete page message
  frontend/src/components/pages/components/page-dropdown/page-dropdown.tsx
Labels: bug

#190 Fix UI-UX
  frontend/src/assets/img/workspace-welcome-logo.png
  frontend/src/common/interfaces/components/button/button.interface.ts
  frontend/src/components/common/confirm-modal/confirm-modal.tsx
  frontend/src/components/common/sign/sign.tsx
  frontend/src/components/common/sign/styles.module.scss
  frontend/src/components/common/with-header/components/header/components/components.ts
  frontend/src/components/common/with-header/components/header/components/nav-disable-notifications/nav-disable-notifications.tsx
  frontend/src/components/common/with-header/components/header/components/nav-notification/components/icon-with-count/icon-with-count.tsx
  frontend/src/components/common/with-header/components/header/components/nav-notification/components/icon-with-count/styles.module.scss
  frontend/src/components/common/with-header/components/header/components/nav-notification/components/natification-item/styles.module.scss
  frontend/src/components/common/with-header/components/header/components/nav-notification/nav-notification.tsx
  frontend/src/components/common/with-header/components/header/components/nav-profile/nav-profile.tsx
  frontend/src/components/common/with-header/components/header/components/nav-profile/styles.scss
  frontend/src/components/common/with-header/components/header/header.tsx
  frontend/src/components/pages/components/components.ts
  frontend/src/components/pages/components/content-editor/content-editor.tsx
  frontend/src/components/pages/components/edit-button/edit-button.tsx
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/components/pages/components/page-contributors/page-contributors.tsx
  frontend/src/components/pages/components/page-dropdown/page-dropdown.tsx
  frontend/src/components/pages/components/page-dropdown/styles.module.scss
  frontend/src/components/pages/components/page-following-users/page-following-users.tsx
  frontend/src/components/pages/components/page-table-of-contents/page-table-of-contents.tsx
  frontend/src/components/pages/components/page-tags/page-tags.scss
  frontend/src/components/pages/components/page-tags/page-tags.tsx
  frontend/src/components/pages/components/popup/components/delete-participant-modal/delete-participant-modal.tsx
  frontend/src/components/pages/components/popup/components/styles.module.scss
  frontend/src/components/pages/pages.tsx
  frontend/src/components/pages/styles.module.scss
  frontend/src/components/profile-info/profile-info.scss
  frontend/src/components/profile-info/profile-info.tsx
  frontend/src/components/settings/components/menu/menu.tsx
  frontend/src/components/settings/components/tag-settings/components/tag-edit/tag-edit.tsx
  frontend/src/components/settings/components/tag-settings/components/tag-item/tag-item.tsx
  frontend/src/components/settings/components/tag-settings/styles.module.scss
  frontend/src/components/settings/components/team-settings/components/popup-invite/components/styles.module.scss
  frontend/src/components/settings/components/users-settings/components/delete-user-modal/delete-user-modal.tsx
  frontend/src/components/settings/components/users-settings/components/user-item/user-item.tsx
  frontend/src/components/settings/components/users-settings/styles.module.scss
Labels: bug

#187 fix: team name and drop-down styles
  frontend/src/components/settings/components/team-settings/components/create-button/create-button.tsx
  frontend/src/components/settings/components/team-settings/components/drop-down/drop-down.tsx
  frontend/src/components/settings/components/team-settings/components/drop-down/styles.scss
  frontend/src/components/settings/components/team-settings/components/item/item.tsx
  frontend/src/components/settings/components/team-settings/components/item/styles.scss
  frontend/src/components/settings/components/team-settings/styles.scss
  frontend/src/components/settings/components/team-settings/team-settings.tsx
Labels: bug

#191 Fix: follow button not displaying current follow status properly
  frontend/src/components/pages/components/page-content/page-content.tsx
Labels: bug

#193 Fix colors in profile-settings
  frontend/src/components/settings/components/profile-settings/profile-settings.tsx
Labels: bug

#196 Fix typo
  frontend/src/components/pages/components/content-editor/content-editor.tsx
Labels: bug

#195 Fix adding tags
  frontend/src/components/pages/components/page-tags/page-tags.tsx
Labels: bug

#192 fix: user table does not display all created teams
  frontend/src/components/settings/components/users-settings/components/user-item/styles.module.scss
  frontend/src/components/settings/components/users-settings/components/user-item/user-item.tsx
Labels: bug

#189 Feat/improve comments
  backend/src/api/routes/page-route.ts
  backend/src/common/interfaces/comment/index.ts
  backend/src/data/entities/comment.ts
  backend/src/data/migrations/1629325183970-comments-tree.ts
  backend/src/data/repositories/comment.repository.ts
  backend/src/data/repositories/index.ts
  backend/src/services/comment.service.ts
  backend/src/services/notification.service.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/enums/app/app.ts
  frontend/src/common/enums/enums.ts
  frontend/src/common/interfaces/comment/comment-normalized.interface.ts
  frontend/src/common/interfaces/comment/index.ts
  frontend/src/components/common/modal/modal.tsx
  frontend/src/components/common/time-ago/time-ago.tsx
  frontend/src/components/common/with-header/styles.module.scss
  frontend/src/components/pages/components/comment-form/comment-form.tsx
  frontend/src/components/pages/components/comment-list/comment-list.tsx
  frontend/src/components/pages/components/comment-list/styles.module.scss
  frontend/src/components/pages/components/comment-section/comment-section.tsx
  frontend/src/components/pages/components/comment-section/styles.module.scss
  frontend/src/components/pages/components/comment/comment.tsx
  frontend/src/components/pages/components/comment/styles.module.scss
  frontend/src/components/pages/components/components.ts
  frontend/src/components/pages/components/delete-modal/delete-modal.tsx
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/components/pages/components/response/response.tsx
  frontend/src/components/pages/components/response/styles.module.scss
  frontend/src/services/comment-api/comment-api.service.ts
  frontend/src/services/index.ts
  frontend/src/store/comments/actions.ts
  frontend/src/store/comments/common.ts
  frontend/src/store/comments/index.ts
  frontend/src/store/comments/schema.ts
  frontend/src/store/comments/slice.ts
  shared/src/common/enums/socket/socket-events.ts
  shared/src/common/interfaces/comment/comment-response.interface.ts
  shared/src/common/interfaces/comment/comment.interface.ts
  shared/src/common/interfaces/comment/index.ts
Labels: enhancement

#202 Fix/table of contents styles
  frontend/src/components/pages/components/page-table-of-contents/page-table-of-contents.tsx
  frontend/src/components/pages/components/page-table-of-contents/styles.module.scss
  frontend/src/components/profile-info/components/activities/styles.module.scss
Labels: bug

#200 Fix button color
  frontend/src/components/settings/components/profile-settings/profile-settings.tsx
Labels: bug

#201 fix: avatars overflow team card width
  frontend/src/components/settings/components/team-settings/components/item/item.tsx
  frontend/src/components/settings/components/team-settings/components/item/styles.scss
  frontend/src/components/settings/components/team-settings/team-settings.tsx
Labels: bug

#205 fix: fixed comments migrations
  backend/src/data/migrations/1629325183970-comments-tree.ts
  backend/src/data/migrations/1629441921901-comments-tree.ts
Labels: bug

#198 fix: hide overflow if the followed page has long title
  frontend/src/components/profile-info/profile-info.scss
Labels: bug

#194 fix: scss files team settings
  frontend/src/components/settings/components/team-settings/components/create-button/create-button.tsx
  frontend/src/components/settings/components/team-settings/components/create-button/styles.module.scss
  frontend/src/components/settings/components/team-settings/components/drop-down/drop-down.tsx
  frontend/src/components/settings/components/team-settings/components/drop-down/styles.module.scss
  frontend/src/components/settings/components/team-settings/components/item/item.tsx
  frontend/src/components/settings/components/team-settings/components/item/styles.module.scss
  frontend/src/components/settings/components/team-settings/styles.module.scss
  frontend/src/components/settings/components/team-settings/team-settings.tsx
Labels: bug

#203 Fix/get table of contents for older versions
  backend/src/api/routes/page-route.ts
  backend/src/data/repositories/page-content.repository.ts
  backend/src/services/page.service.ts
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/services/page-api/page-api.service.ts
Labels: bug

#207 fix: delete page modal text
  frontend/src/components/pages/components/page-content/page-content.tsx
Labels: bug

#208 fix nitification message & simple fix deleting in team
  backend/src/services/team.service.ts
  frontend/src/components/settings/components/team-settings/components/popup-invite/popup-invite.tsx
Labels: bug

#206 fix: returned deleted migration
  backend/src/data/migrations/1629325183970-comments-tree.ts
Labels: bug

#211 Fix delete comment
  backend/src/data/repositories/comment.repository.ts
  backend/src/data/repositories/notification.repository.ts
  backend/src/services/comment.service.ts
  backend/src/services/notification.service.ts
  frontend/src/components/common/with-header/components/header/components/nav-notification/nav-notification.tsx
  frontend/src/store/comments/slice.ts
  shared/src/common/enums/socket/socket-events.ts
Labels: bug

#212 fix: fixed comment expansion
  frontend/src/components/pages/components/page-content/page-content.tsx
Labels: bug

#210 fix: assign permissions table header text
  frontend/src/components/pages/components/popup/popup.tsx
Labels: bug

#209 fix: page layout, add popover for page heading
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/components/pages/components/page-content/styles.module.scss
  frontend/src/components/settings/components/users-settings/components/user-item/styles.module.scss
Labels: bug

#219 fix: made teams scoped to workspace
  backend/src/api/routes/team-route.ts
  backend/src/data/repositories/team.repository.ts
  backend/src/services/team.service.ts
Labels: bug

#220 Fix/activities markdown
  frontend/src/components/profile-info/components/activities/activities.tsx
  frontend/src/components/profile-info/components/activities/styles.module.scss
Labels: enhancement

#225 fix: spec chars are not allowed in tags now
  frontend/src/components/settings/components/tag-settings/components/tag-add/tag-add.tsx
  frontend/src/store/tags/actions.ts
Labels: bug

#222 fix: redirect to the latest version of the page by clicking on activity
  frontend/src/components/profile-info/components/activities/activities.tsx
Labels: bug

#223 Fix/show activities in profile from current workspace
  backend/src/api/routes/user-route.ts
  backend/src/data/repositories/activity.repository.ts
  backend/src/services/user.service.ts
Labels: bug

#226 New/teams tab in settings for user
  backend/src/api/routes/team-route.ts
  backend/src/data/repositories/user.repository.ts
  backend/src/services/team.service.ts
  frontend/src/components/settings/components/menu/menu.tsx
  frontend/src/components/settings/components/team-settings/components/popup-invite/popup-invite.tsx
  frontend/src/components/settings/components/team-settings/team-settings.tsx
  frontend/src/services/team-api.service.ts
  frontend/src/store/teams/actions.ts
  frontend/src/store/teams/common.ts
  frontend/src/store/teams/slice.ts
Labels: enhancement

#235 fix migration to create a column workspaceid in skills
  backend/src/data/migrations/1629818873436-add-workspaceid-to-skills.ts
Labels: bug

#238 fix: unfollow child pages
  backend/src/services/page.service.ts
  frontend/src/components/profile-info/profile-info.tsx
Labels: bug

#239 New/global search
  backend/.env.example
  backend/package-lock.json
  backend/package.json
  backend/src/api/routes/page-route.ts
  backend/src/common/interfaces/page/index.ts
  backend/src/common/mappers/page/map-search-hit-elastice-page-content-to-found-page-content.ts
  backend/src/data/migrations/1629555194389-create-draft-table.ts
  backend/src/data/repositories/team-permission.repository.ts
  backend/src/data/repositories/user-permission.repository.ts
  backend/src/elasticsearch/elasticsearch.ts
  backend/src/elasticsearch/entities/index.ts
  backend/src/elasticsearch/entities/page-content.entity.ts
  backend/src/elasticsearch/index.ts
  backend/src/elasticsearch/repositories/index.ts
  backend/src/elasticsearch/repositories/page-content.repository.ts
  backend/src/elasticsearch/seeders/page-content.seeder.ts
  backend/src/elasticsearch/seeders/seeders.ts
  backend/src/env.ts
  backend/src/services/page.service.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/interfaces/pages/index.ts
  frontend/src/components/common/with-header/components/header/components/search/search.tsx
  frontend/src/components/common/with-header/components/header/components/search/styles.module.scss
  frontend/src/hooks/hooks.ts
  frontend/src/services/page-api.service.ts
  shared/src/common/interfaces/pages/found-page-content.interface.ts
  shared/src/common/interfaces/pages/index.ts
Labels: enhancement

#247 fix: lower elastisearch version
  backend/package-lock.json
  backend/package.json
Labels: bug

#246 Fix/remove focus in activities menu dropdown item & add spinner on loading
  backend/src/common/mappers/page/map-search-hit-elastice-page-content-to-found-page-content.ts
  backend/src/data/migrations/1629807729515-add-notifications-settings.ts
  frontend/src/components/profile-info/components/activities/activities.tsx
  frontend/src/components/profile-info/components/activities/styles.module.scss
  frontend/src/store/activities/actions.ts
Labels: bug

#245 fix: added prettier ignore
  .prettierignore
Labels: enhancement

#248 Fix/elasticsearch seeding
  backend/src/elasticsearch/seeders/seeders.ts
Labels: bug

#249 Fix/activities long comment width
  backend/src/data/migrations/1629138247028-add-notifications.ts
  backend/src/data/migrations/1629190860113-add-default-status-value-not-null.ts
  backend/src/data/migrations/1629195023370-added-deleted-status.ts
  backend/src/data/migrations/1629292188397-add-entity-type-team.ts
  backend/src/data/migrations/1629807729515-add-notifications-settings.ts
  backend/src/elasticsearch/repositories/page-content.repository.ts
  backend/src/services/page.service.ts
  frontend/src/components/profile-info/components/activities/styles.module.scss
Labels: bug

#252 fix: fixed nested comments deletion
  backend/package-lock.json
  backend/src/data/entities/comment.ts
  backend/src/data/migrations/1629900305959-comments-relation.ts
  frontend/package-lock.json
Labels: bug

#251 Fix/comments mentions
  backend/src/api/routes/workspace-route.ts
  backend/src/common/helpers/is-notify.helper.ts
  backend/src/common/regex/index.ts
  backend/src/common/types/index.ts
  backend/src/common/types/mail-gen.type.ts
  backend/src/common/types/notification-gen.type.ts
  backend/src/common/utils/index.ts
  backend/src/common/utils/mail/comment-mail.util.ts
  backend/src/common/utils/mail/index.ts
  backend/src/common/utils/mail/reply-mail.util.ts
  backend/src/common/utils/mailer.util.ts
  backend/src/common/utils/mention.util.ts
  backend/src/common/utils/notifications/comment-notification.util.ts
  backend/src/common/utils/notifications/index.ts
  backend/src/common/utils/notifications/mention-notification.util.ts
  backend/src/data/repositories/comment.repository.ts
  backend/src/data/repositories/notification-settings.repository.ts
  backend/src/data/repositories/notification.repository.ts
  backend/src/data/repositories/page.repository.ts
  backend/src/services/comment.service.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/regex/index.ts
  frontend/src/components/common/link/link.tsx
  frontend/src/components/common/modal/modal.tsx
  frontend/src/components/common/modal/styles.module.scss
  frontend/src/components/pages/components/comment-form/styles.module.scss
  frontend/src/components/pages/components/comment-section/comment-section.tsx
  frontend/src/components/pages/components/comment-section/components/comment-form/comment-form.tsx
  frontend/src/components/pages/components/comment-section/components/comment-form/styles.module.scss
  frontend/src/components/pages/components/comment-section/components/comment-list/comment-list.tsx
  frontend/src/components/pages/components/comment-section/components/comment-list/styles.module.scss
  frontend/src/components/pages/components/comment-section/components/comment/comment.tsx
  frontend/src/components/pages/components/comment-section/components/comment/styles.module.scss
  frontend/src/components/pages/components/comment-section/components/delete-modal/delete-modal.tsx
  frontend/src/components/pages/components/comment-section/components/emoji/emoji.tsx
  frontend/src/components/pages/components/comment-section/components/emoji/styles.scss
  frontend/src/components/pages/components/comment-section/components/index.ts
  frontend/src/components/pages/components/comment/comment.tsx
  frontend/src/components/pages/components/components.ts
  frontend/src/helpers/parse-mentions.helper.tsx
  frontend/src/services/comment-api.service.ts
  frontend/src/store/comments/actions.ts
  frontend/src/store/comments/slice.ts
  shared/src/common/interfaces/comment/comment-request.interface.ts
  shared/src/common/regex/index.ts
  shared/src/common/regex/mentions.ts
  shared/src/common/validations/create-comment-schema.ts
  shared/src/index.ts
Labels: enhancement

#255 fix: image size in activities feed
  frontend/src/components/profile-info/components/activities/styles.module.scss
Labels: bug

#257 Fix/style of the buttons
  frontend/src/components/pages/components/popup/popup.tsx
  frontend/src/components/profile-info/components/activities/activities.tsx
  frontend/src/components/settings/components/profile-settings/components/crop-avatar/crop-avatar.tsx
Labels: enhancement

#275 feat: follow/unfollow child pages in modal
  backend/src/services/user.service.ts
  frontend/src/components/pages/components/follow-modal/follow-modal.tsx
  frontend/src/components/pages/components/page-content/page-content.tsx
  frontend/src/components/profile-info/profile-info.tsx
  frontend/src/components/settings/components/profile-settings/profile-settings.tsx
  frontend/src/store/pages/actions.ts
Labels: enhancement

#278 fix: share link modal text
  frontend/src/components/pages/components/share-modal/components/link-item/link-item.tsx
  frontend/src/components/pages/components/share-modal/components/link-item/styles.module.scss
Labels: bug

#291 Add login with github
  backend/src/api/routes/auth-route.ts
  backend/src/services/auth.service.ts
  frontend/src/components/auth/login-github/login-github.tsx
  frontend/src/components/common/sign/sign.tsx
  frontend/src/components/common/sign/styles.module.scss
  frontend/src/services/auth-api.service.ts
  frontend/src/services/index.ts
  frontend/src/services/notification-settings-api.service.ts
  frontend/src/store/auth/actions.ts
  shared/src/common/enums/http/http-error-message.enum.ts
Labels: enhancement

#288 correct permissions to manage page tags
  frontend/src/components/pages/components/page-tags/page-tags.tsx
Labels: bug
